export const SET_QUERY = 'SET_QUERY';
export const GET_ITEMS = 'GET_ITEMS';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_ERROR = 'GET_ITEMS_ERROR';
export const GET_ITEM_BY_ID = 'GET_ITEM_BY_ID';
export const GET_ITEM_BY_ID_SUCCESS = 'GET_ITEM_BY_ID_SUCCESS';
export const GET_ITEM_BY_ID_ERROR = 'GET_ITEM_BY_ID_ERROR';
